### ISSUE TITLE
Replace ${} terraform notation in example with more clear placeholders

### ISSUE THREAD

**Issue by jeanduplessis** [crossplane/upjet#129]
### What problem are you facing?

The `${}` notation in the marketplace exposed examples are causing confusion for some users. 

`${}` notation creates impressions that the Crossplane will automatically interpolate the value.

### How could Upjet help solve your problem?

We need to find an alternative to `${}` notation that would be clear and obvious to customers.

Some ideas:
* Just add comments next to placeholders, e.g.
```
tenantId: ${data.azurerm_client_config.current.tenant_id}  # replace the value with your Azure tenant id
```
* Replace placeholders with example values before the xpkg packaging and also amend it with comment
```
tenantId: b9925bc4-8383-4c37-b9d2-fa456d1bb1c7  # replace the value with your Azure tenant id
```

**Comment by muvaf** [comment]
Uptest replaces these with the real values right before running the tests. I think we can replace them with dummy values right before we submit the provider package to marketplace. Though the format of the dummy value better matches the real value to give a clue, so expanding [this data source structure](https://github.com/upbound/uptest/blob/aa9305a/internal/prepare.go#L117) to have two values for each could be a good idea.
