### ISSUE TITLE
Update broken links to Crossplane documentation

### ISSUE THREAD

**Issue by mergenci** [crossplane/upjet#271]
### What problem are you facing?

In documentation, 5/6 links to Crossplane documentation are broken — they return 404 Not Found. Here are the links to Crossplane documentation I found using `grep "docs/v1." docs/*` (link titles are links to lines in the version control):

1. add-new-resource-long.md:[[the external name documentation](https://github.com/upbound/upjet/blob/main/docs/add-new-resource-long.md?plain=1#L20)]: https://crossplane.io/docs/v1.7/concepts/managed-resources.html#external-name
2. add-new-resource-long.md:[[handle dependencies](https://github.com/upbound/upjet/blob/main/docs/add-new-resource-long.md?plain=1#L267)]: https://crossplane.io/docs/v1.7/concepts/managed-resources.html#dependencies
3. add-new-resource-long.md:[[connection details](https://github.com/upbound/upjet/blob/main/docs/add-new-resource-long.md?plain=1#L367)]: https://crossplane.io/docs/v1.7/concepts/managed-resources.html#connection-details
4. reference-generation.md:[[Dependencies](https://github.com/upbound/upjet/blob/main/docs/reference-generation.md?plain=1#L7)]: https://crossplane.io/docs/v1.7/concepts/managed-resources.html#dependencies
5. testing-instructions.md:[[the documentation](https://github.com/upbound/upjet/blob/main/docs/testing-instructions.md?plain=1#L35)]: https://crossplane.io/docs/v1.9/getting-started/install-configure.html#install-configuration-package
6. _This link is not broken_. testing-instructions.md:[[Late Initialization](https://github.com/upbound/upjet/blob/main/docs/testing-instructions.md?plain=1#L223)]: https://crossplane.io/docs/v1.9/concepts/managed-resources.html#late-initialization

For convenience, I've located relevant Crossplane documentation before they were removed from version control, in case you would like to see what broken links used to refer to: [v1.9](https://github.com/crossplane/docs/tree/6db0791713ccd806648ecf356fe9b1c7baf47b2f/content/v1.9), [v1.7](https://github.com/crossplane/docs/tree/c3e30568d07700c9bba7c1d3ad6d7b575220d734/content/docs/v1.7)

### How could Upjet help solve your problem?

Some of the links might have gone broken because of simple title changes in the Crossplane documentation. Those should be easy to fix. Some of them, though, refer to obsolete features (Number 5 above?); therefore, may require updating Upjet documentation accordingly.

**Comment by jeanduplessis** [comment]
@mergenci I am in the process of re-writing the Upjet documentation to live on docs.upbound.io. During this I am fixing up links as needed. We can keep this issue open and close it once the documentation is published on docs.upbound.io.

**Comment by jeanduplessis** [comment]
With the donation of Upjet to the Crossplane project we will not be publishing documentation on docs.upbound.io anymore. We should address these reported broken links.

**Comment by jeanduplessis** [comment]
These links are now outdated with recent changes to the docs.
