### ISSUE TITLE
API Call Counter

### ISSUE THREAD

**Issue by humoflife** [crossplane/upjet#297]
### What problem are you facing?

Crossplane users would like to know how many API calls to which APIs a provider makes. Please expose an API call counter metric at the provider metric interface.

There should be a roll up metric for all API calls, all API calls per API version, and a counter for each separate API/version. Those three categories could be satisfied through labels for the same metric. They would allow a quick view of overarching trend changes after updating or introducing new compositions, or additional claims. They would also inform about API version adoption, and provide an overview of which APIs are more popular and to which degree.

### How could Upjet help solve your problem?

Implement and expose the following metrics at port 8080/metrics for all providers that are generated with Upjet.

api_call_count {group="...", version="...", kind="..."}

**Comment by candonov** [comment]
This is great! It would be useful to have a simple counter per each API and also a metric to calculate the duration of those api calls.

**Comment by haarchri** [comment]
just for reference from crossplane-contrib/provider-aws:

https://github.com/crossplane-contrib/provider-aws/pull/1964
https://github.com/crossplane-contrib/provider-aws/pull/1862

**Comment by jeanduplessis** [comment]
@humoflife what is the core problem users are trying to solve by getting access to the API call counts?

**Comment by stevendborrelli** [comment]
Since it wasn't linked back here, this was added in provider-aws 1.3.0 via <https://github.com/crossplane-contrib/provider-upjet-aws/pull/1241>

**Comment by jeanduplessis** [comment]
I'm going to close this issue as the implementation isn't Upjet specific, but rather something that has to be implemented specifically for each provider.
