### ISSUE TITLE
Any plans for a Oracle Oci provider?

### ISSUE THREAD

**Issue by rockchico** [crossplane/upjet#433]
### What problem are you facing?

I would like to generate a crossplane provider from [TF Provider OCI](https://registry.terraform.io/providers/oracle/oci/latest/docs). 

There's a project called [crossplane-provider-oci](https://github.com/oracle-samples/crossplane-provider-oci/tree/main), it seems that they tried to achieve that. I tried it and it works fine, but I missed some CRDS related to [autonomous database](https://registry.terraform.io/providers/oracle/oci/latest/docs/resources/database_autonomous_database)

https://doc.crds.dev/github.com/oracle-samples/crossplane-provider-oci

### How could Upjet help solve your problem?

There's a roadmap to launch an official Oracle OCI crossplane provider??

Maybe somebody could help me to generate a full TF resource OCI provider using Upjet??

**Comment by rockchico** [comment]
> The Crossplane project has no plans for an official OCI provider, it would need to be driven by the community. It could certainly be hosted in crossplane-contrib once it is ready. I would suggest using that project as a starting point _if the licensing allows for that_ or otherwise start from [provider-upjet-template](https://github.com/crossplane/upjet-provider-template) and you can use the Crossplane Slack channels to ask for help and find others who may be willing to help.

Thanks @bobh66

**Comment by jbw976** [comment]
Sharing this relevant discussion post too 🤩 
https://github.com/crossplane/crossplane/discussions/5194

**Comment by rockchico** [comment]
Just want to share that I managed to build my custom Oracle OCI Crossplane provider based on [upjet-provider-template](https://github.com/crossplane/upjet-provider-template). I followed the instructions, it works really well. I was able to add all the necessary resources CRDs and build a new provider package to handle the creation of [OCI Autonomous Database] (https://registry.terraform.io/providers/oracle/oci/latest/docs/resources/database_autonomous_database) that I was missing.

[custom oci crossplane provider](https://github.com/rockchico/provider-oci)

Thank you all

**Comment by jeanduplessis** [comment]
Thank you for the update @rockchico
