### ISSUE TITLE
Some resources get stuck in `NotFound` state during deletion

### ISSUE THREAD

**Issue by muvaf** [crossplane/upjet#67]
### What happened?

When the resource is deleted, it gets stuck in `refresh failed: NotFound` state in some resources.

### How can we reproduce it?

See https://github.com/upbound/provider-aws/issues/25

**Comment by nekr0z** [comment]
@jeanduplessis is this fixed? Is there now a way to make it so that "children" resources do get deleted when the "parent" resource does?

There are uptest hooks, of course, but those only work for tests.

**Comment by jeanduplessis** [comment]
@nekr0z automatic cleanup of child resources when deleting the parent resource is not a feature we support. Your best bet is to model the relationship with the [XP Usage API](https://docs.crossplane.io/latest/concepts/usages/) to ensure resources are deleted in the correct order.
