### ISSUE TITLE
Explicit reference causes import cycle error

### ISSUE THREAD

**Issue by donovanmuller** [crossplane/upjet#96]
### What happened?

With one specific GCP resource (`google_service_networking_peered_dns_domain `) configured with an explicit `Network` reference, running `make reviewable` results in an [error](https://github.com/upbound/official-providers/runs/7951516684?check_suite_focus=true#step:9:30) as described in this https://github.com/upbound/official-providers/pull/518#discussion_r943598464. Note that the `Network` reference is not automatically added via Upjet either.

https://github.com/upbound/official-providers/blob/7ac76a2a7d155838a7cc479b6dd8352357b1d79c/provider-gcp/config/cloudplatform/config.go#L93-L101

[Removing](https://github.com/upbound/official-providers/pull/518/commits/12dc7be67b7bb4b7d956d4121f36619ea7fbcae5#diff-7605d33a7111a5a72caa05b139361688d16236f1da6a0bc24a1e9c6943e8b6acL94-L97) the explicit reference allows for successful generation.

### How can we reproduce it?

* Checkout commit 93afafc9361dfdf96bd2aa91d20cd2bdc29bebf3
* `make && cd provider-gcp && make reviewable`

### What environment did it happen in?

* Crossplane Version: `v1.9.0-up.2`
* Provider Name: `provider-gcp`
* Provider Version: development - see https://github.com/upbound/official-providers/pull/518

**Comment by luebken** [comment]
Severity:low as we currently don't encounter this often. Please add your use-case if you encounter this.

**Comment by haarchri** [comment]
we have this case also for an zscaler provider

```
(⎈|kind-sop-local:N/A)➜  crossplane-provider-zpa git:(master) ✗ make run
19:34:31 [ .. ] go build linux_arm64
package github.com/xx/crossplane-provider-zpa/cmd/provider
        imports github.com/xx/crossplane-provider-zpa/apis
        imports github.com/xx/crossplane-provider-zpa/apis/zpaapplicationsegment/v1alpha1
        imports github.com/xx/crossplane-provider-zpa/apis/zpaservergroup/v1alpha1
        imports github.com/xx/crossplane-provider-zpa/apis/zpaapplicationserver/v1alpha1
        imports github.com/xx/crossplane-provider-zpa/apis/zpaservergroup/v1alpha1: import cycle not allowed
19:34:31 [FAIL]
make: *** [go.build] Error 1
```
